### ISSUE TITLE
Issue with node_modules/cssstyle/lib/properties.js

### ISSUE THREAD

**Issue by klango** [mhagmajer/meteor-whiteboard#2]
Hi,
when running meteor I get:

Unable to resolve some modules:

  "@babel/runtime/helpers/slicedToArray" in /meteor-whiteboard-master/client/main.js (web.browser.legacy)
                                            
                                        
=> Errors prevented startup:                  
   
   While building for web.browser:
   node_modules/cssstyle/lib/properties.js:5029:9: Identifier 'parse' has already been declared (5029:9)
   
   While building for web.browser.legacy:
   node_modules/cssstyle/lib/properties.js:5029:9: Identifier 'parse' has already been declared (5029:9)
   
=> Your application has errors. Waiting for file change.
Unexpected mongo exit code 14. Restarting.    

Any ideas?

**Comment by klango** [comment]
problems with permissions on mongo. resolved.

**Comment by AnthonyTwoBears** [comment]
Hi,   I'm getting the exact same problem with the same error, how did you resolve it?  What does problems with permissions on mongo mean ?

Thanks
